# 公共配置文件
spring:
  application:
    name: jinzi-generator-web-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.222.249:3306/my_db
    username: root
    password: xy123456
  mail:
    host: smtp.qq.com     #默认平台服务地址无需更改
    username: 2670253693@qq.com   #自己邮箱号
    password: xhjkdddfcbxpdhjh    #这是我们在刚刚开启POP3/SMTP服务时收到的授权码(如果忘了把服务重开一次!)
    default-encoding: utf-8 #改编码格式
    protocol: smtp
    port: 25 #端口号
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 124.223.222.249
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8120
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
cos:
  client:
    accessKey: 1310252632
    secretKey: AKIDVvEKKH1W5d3LUWSI0oU2MZedQ5sX0XzL
    region: ap-chengdu
    bucket: jinzi-generator-1310252632
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jinzi.web.controller
