# 公共配置文件
spring:
  session:
    store-type: redis
    timeout: 2592000
  redis:
    database: 1
    host: 124.223.222.249
    port: 6379
    timeout: 5000
    password: 123456
  application:
    name: jinzi-generator-web-backend
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.222.249:3306/my_db
    username: root
    password: xy123456
  mail:
    host: smtp.qq.com     #默认平台服务地址无需更改
    username: 2670253693@qq.com   #自己邮箱号
    password: xhjkdddfcbxpdhjh    #这是我们在刚刚开启POP3/SMTP服务时收到的授权码(如果忘了把服务重开一次!)
    default-encoding: utf-8 #改编码格式
    protocol: smtp
    port: 25 #端口号
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8120
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jinzi.web.controller
cos:
  client:
    accessKey: "AKIDBSoO4qhbZYaeDt1LkCgGubzNmChAe8fB"
    secretKey: "cBoOvQwfM0eRBHQYgmw8Tm8Sl1QwTyY7"
    region: "ap-chengdu"
    bucket: "jinzi-generator-1310252632"
# 微信支付配置
wx:
  pay:
    appId: wxxxxxxxxx67e8dc
    mchId: 1x0xxxx68
    apiV3Key: xxxxxbxxx3xxxx3xxx4
    privateKeyPath: classpath:/pem/apiclient_key.pem
    privateCertPath: classpath:/pem/apiclient_cert.pem
    # 本地测试用ngrok内网穿透，这个内网穿透地址，可以修改为自己的。上线修改为后端的接口地址即可
    notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order

# 支付宝支付配置
alipay:
  appId: 9021000136636139
  sellerId: 2xxxxxxxxxxxxx7
  # 本地测试用ngrok内网穿透，这个内网穿透地址，可以修改为自己的。上线修改为后端的接口地址即可
  notifyUrl: https://beloved-massive-sheepdog.ngrok-free.app/api/order/notify/order
  #  支付成功之后跳转到的页面
  returnUrl: http://localhost:8000/account/center
  # 私钥
  private-key: xxxxxxxxxx
  # 公钥
  ali-pay-public-key: xxxxxxxxxxxxxxxx
